window.OW_DATA = {
  version: "2026-09",
  subroles: {"tank":["Fuerte","Iniciador","Valeroso"],"damage":["En el blanco","Flanqueador","Especialista","Reconocimiento"],"support":["Estratega","Médico","Superviviente"]},
  heroes: [
    { id: "dmon", name: "D.Mon", role: "tank", subrole: "Valeroso", retos: [
      {t: "Cada vez que te revienten el meka y salgas a pie, tienes que conseguir una baja con la ametralladora antes de volver a llamar al meka con el ulti.", d: 3},
      {t: "Surging Strike solo vale si empotras a alguien contra una pared. Cada Surging Strike al aire: 3 sentadillas al acabar la ronda.", d: 2},
      {t: "Prohibido usar Fusion Repeater: solo puedes pegar con el Plasma Saber y las habilidades. Modo samurái de verdad.", d: 2},
      {t: "Tu Limit Break tiene que pillar a 3 o más enemigos. Si pilla a menos, el chat elige tu próxima ventaja.", d: 3},
      {t: "Cada vez que uses Propulsors tienes que gritar «¡BUSAN!» por el micro. Si se te olvida, 1 trago de agua.", d: 1},
      {t: "Mantén Power Barrier levantada al menos 5 segundos seguidos en cada pelea de equipo antes de soltarla. El chat lleva la cuenta.", d: 1},
      {t: "Gana un 1v1 contra el tanque enemigo usando solo el Plasma Saber y Surging Strike.", d: 3},
      {t: "Solo puedes coger la ventaja menor Beast Within y tienes que curar tu escudo al menos 3 veces seguidas a espadazos en una pelea.", d: 2},
      {t: "Juega toda la partida siendo el primero en entrar a cada pelea: ningún compañero puede pasar delante de tu barrera.", d: 2},
      {t: "Cada baja con el Plasma Saber se celebra con el emote de victoria o un spray en el cadáver.", d: 1},
      {t: "Tras usar el ulti, tienes que hacer Surging Strike en los 3 segundos siguientes a alguien marcado por el daño amplificado.", d: 2},
      {t: "Prohibido retroceder con Propulsors: solo puedes usarlos hacia delante o de lado.", d: 2},
      {t: "Antes de cada pelea, apunta con el sable al equipo enemigo y usa la línea de voz de «¡Vamos!». Sin ritual no hay carga.", d: 1},
      {t: "Cada vez que te sacan del meka tienes que decir una frase de pro gamer coreana inventada por el chat.", d: 1}
    ] },
    { id: "dva", name: "D.Va", role: "tank", subrole: "Iniciador", retos: [
      {t: "Cada Autodestrucción tiene que llevarse al menos una baja. Si no mata a nadie, 10 flexiones.", d: 2},
      {t: "Grita «¡NERF THIS!» por el micro antes de cada Autodestrucción, al mismo tiempo que la voz del juego.", d: 1},
      {t: "Tira a un enemigo al vacío empujándolo con Propulsores.", d: 3},
      {t: "Consigue una baja con la pistola de D.Va a pie después de que te revienten el meka.", d: 2},
      {t: "Llama al meka encima de un enemigo y mátalo aplastándolo. El chat da permiso para gritar como en un torneo.", d: 3},
      {t: "Solo puedes volar con Propulsores hacia la backline enemiga: prohibido usarlos para huir hacia tu equipo.", d: 2},
      {t: "Cada pelea empieza con tu Propulsor contra el jugador más alejado del equipo enemigo.", d: 2},
      {t: "Toda la partida sin usar los Micromisiles. Solo cañones de fusión y matriz.", d: 1},
      {t: "Cada vez que la matriz te salve a un compañero de morir, tienes que decir «de nada, bebé» en el chat de voz.", d: 1},
      {t: "Mantén la Matriz defensiva encendida hasta vaciarla del todo en cada pelea: ni un segundo de recurso desperdiciado.", d: 1},
      {t: "Usa la Autodestrucción como zona: tiene que echar a todo el equipo enemigo del punto sin necesidad de matar.", d: 2},
      {t: "Consigue una baja con los Micromisiles mientras vuelas con Propulsores.", d: 2},
      {t: "Tras cada baja en el meka, haz el emote o la pose de «victoria» de D.Va encima del cadáver antes de seguir.", d: 1},
      {t: "Consigue 3 bajas en una misma vida sin salir del meka ni una vez.", d: 3}
    ] },
    { id: "domina", name: "Domina", role: "tank", subrole: "Valeroso", retos: [
      {t: "Cada Sonic Repulsors tiene que empotrar a alguien contra una pared para aturdirlo. Cada fallo: 5 flexiones.", d: 2},
      {t: "Panopticon tiene que encerrar al menos a 2 enemigos. Si solo pillas a uno, el chat elige tu mira durante 2 minutos.", d: 3},
      {t: "Tank de poke de verdad: prohibido pisar más allá de la mitad del mapa hasta que tu equipo tenga la primera baja.", d: 2},
      {t: "Mueve tu Barrier Array a una posición nueva en cada pelea y avisa por el micro a dónde la mueves antes de hacerlo.", d: 1},
      {t: "Detona la Crystal Charge justo encima de un support enemigo y mátalo con el siguiente disparo del Photon Magnum.", d: 3},
      {t: "Juega con aire de villana élite: cada baja tienes que decir «insignificante» con tu mejor voz de jefa de Talon.", d: 1},
      {t: "Consigue un combo Repulsors contra la pared + Crystal Charge sobre el aturdido.", d: 2},
      {t: "Tu barrera no puede romperse nunca: si te la rompen entera, un trago de agua cada vez.", d: 2},
      {t: "Aprovecha la pasiva: recupera escudos a base de habilidades y di en voz alta cuántas veces te salva la vida.", d: 1},
      {t: "Solo puedes disparar el Photon Magnum a cargo completo: nada de tiros sueltos a media distancia.", d: 2},
      {t: "Tras cada Panopticon, pon un spray delante de la prisión y di «bienvenidos a mi colección».", d: 1},
      {t: "Encierra al tanque enemigo con Panopticon y que tu equipo lo mate dentro.", d: 3},
      {t: "Juega toda la partida detrás de tu Barrier Array: si te quedas fuera de ella más de 3 segundos, una flexión.", d: 2}
    ] },
    { id: "doomfist", name: "Doomfist", role: "tank", subrole: "Iniciador", retos: [
      {t: "Cada Puño cohete tiene que estampar a alguien contra la pared. Puño al aire o sin pared: 5 flexiones.", d: 2},
      {t: "Consigue el puño cargado con Bloqueo de poder en cada pelea y grítalo cuando lo tengas.", d: 2},
      {t: "Mata a un support enemigo con Meteoro directo en el centro. Nada de rozar, impacto limpio.", d: 3},
      {t: "Prohibido disparar la Mano cañón: solo puños, golpe sísmico y meteoro.", d: 2},
      {t: "Cada vez que entres a la backline tienes que salir vivo. Si mueres dentro, bebe agua y di «el mejor de todos los tiempos» con voz derrotada.", d: 2},
      {t: "Interrumpe un ulti enemigo con Puño cohete o Golpe sísmico (Barrage, Flor de la muerte, Dead Eye…).", d: 3},
      {t: "Usa Meteoro solo para escapar: nunca para hacer daño. Si matas con él, cuenta igual, pero no puedes buscarlo.", d: 1},
      {t: "Antes de cada puño cargado, di en voz alta a quién se lo vas a dar. Si le das a otro, cambia la sensibilidad +10%.", d: 2},
      {t: "Combo clásico: Golpe sísmico, Puño cohete y remate con la Mano cañón al mismo enemigo, todo seguido. Consíguelo en tres peleas distintas.", d: 3},
      {t: "Durante toda la partida, tras cada baja tienes que cantar «I am Doomfist» en inglés macarrónico.", d: 1},
      {t: "Prohibido atacar al tanque enemigo: solo puedes pegar a daño y apoyo.", d: 2},
      {t: "Empotra a dos enemigos a la vez contra la misma pared con un solo Puño cohete.", d: 3},
      {t: "El chat elige tus dos ventajas (menor y mayor) en cuanto se desbloqueen, sin opción a quejarte.", d: 1}
    ] },
    { id: "hazard", name: "Hazard", role: "tank", subrole: "Iniciador", retos: [
      {t: "Cada Jagged Wall tiene que empujar a alguien. Muro que no pilla a nadie: 5 sentadillas.", d: 2},
      {t: "Tu Downpour tiene que atrapar a 3 o más enemigos. Si pilla menos, el chat decide tu siguiente ventaja.", d: 3},
      {t: "Aguanta con Spike Guard en mitad del equipo enemigo hasta vaciar el recurso y sal vivo.", d: 2},
      {t: "Solo puedes entrar a las peleas con Violent Leap por encima del enemigo, nunca andando.", d: 2},
      {t: "Empuja a dos enemigos a la vez con la misma Jagged Wall.", d: 2},
      {t: "Cada vez que uses Violent Leap tienes que gritar «¡PINCHOS!»", d: 1},
      {t: "Escala una pared con la movilidad de Hazard y cae encima de la backline enemiga en la primera pelea de cada ronda.", d: 2},
      {t: "Mantén Spike Guard hasta que se te vacíe el recurso una vez por pelea: modo erizo total.", d: 1},
      {t: "Consigue una baja con los pinchos de Spike Guard, sin disparar.", d: 3},
      {t: "Prohibido usar el arma principal cuando el enemigo esté a más de 10 metros: solo escopetazo a quemarropa.", d: 2},
      {t: "Tras cada Downpour, di el nombre de todos los que has pillado antes de que acabe el efecto.", d: 1},
      {t: "Consigue que tu equipo mate a todos los atrapados en tu Downpour (team wipe desde tu ulti).", d: 3},
      {t: "Cada vez que ganéis una pelea, escala la pared más alta cerca del objetivo y haz un emote arriba.", d: 1}
    ] },
    { id: "junker-queen", name: "Junker Queen", role: "tank", subrole: "Valeroso", retos: [
      {t: "Cada vez que recuperes el Cuchillo dentado con un enemigo pegado, tienes que decir «ven con mamá».", d: 1},
      {t: "Masacre tiene que pillar a 2 enemigos o más cada vez. Si pilla a uno, 5 flexiones.", d: 2},
      {t: "Estampida tiene que herir a 3 enemigos o más. Si no, el chat te pone la sensibilidad a su gusto un minuto.", d: 3},
      {t: "Grito de mando solo cuando tu equipo esté a punto de entrar: avisa «¡A POR ELLOS!» antes de cada uno.", d: 1},
      {t: "Mata a alguien trayéndolo con el cuchillo a su muerte (tirón + remate con escopeta o hacha).", d: 2},
      {t: "Solo puedes tirar el cuchillo a supports. Nada de tanques ni daños.", d: 2},
      {t: "Toda la partida hablando como reina de Junkertown: acento macarra y amenazas cada vez que alguien te cure.", d: 1},
      {t: "Consigue 3 bajas en una misma Estampida + remate.", d: 3},
      {t: "Prohibido retroceder a curarte: solo te curas por las heridas de tus golpes y los supports.", d: 2},
      {t: "Pesca con el cuchillo a un enemigo que esté fuera de tu línea de visión y remátalo.", d: 3},
      {t: "Cada Masacre que no hiera a nadie: bebe agua.", d: 1},
      {t: "Salva a un aliado con Grito de mando justo cuando está a punto de morir; el chat lo valida.", d: 2},
      {t: "Tras ganar cada pelea, sube al objetivo, haz el emote más macarra que tengas y proclama «¡Aquí manda la reina!».", d: 1}
    ] },
    { id: "mauga", name: "Mauga", role: "tank", subrole: "Fuerte", retos: [
      {t: "Enciende al enemigo con una ametralladora y remátalo con la otra: cada baja tiene que tener enemigo ardiendo.", d: 1},
      {t: "Jaula de combate tiene que dejar dentro al menos a 3 enemigos. Si no, 10 sentadillas.", d: 3},
      {t: "Usa Carga imparable para derribar a 2 enemigos en una misma carga.", d: 3},
      {t: "Sobrecarga cardíaca tiene que salvar a un compañero que está a punto de morir. Grita «¡CORAZÓN!» al activarla.", d: 2},
      {t: "Toda la partida disparando solo con una ametralladora (un solo botón de fuego).", d: 2},
      {t: "Cada vez que mates a alguien, tienes que reírte como Mauga. Si el chat no lo oye, no cuenta.", d: 1},
      {t: "Cada vez que ganéis una pelea, haz un emote de baile en el objetivo. Mauga es el alma de la fiesta.", d: 1},
      {t: "Prohibido dejar de disparar más de 3 segundos cuando haya enemigos a la vista. Modo gatillo fácil.", d: 1},
      {t: "Dentro de tu Jaula, gana el 1v1 contra el tanque enemigo.", d: 3},
      {t: "Carga imparable siempre hacia delante y hacia el enemigo; nunca para retirarte.", d: 2},
      {t: "Juega en el centro del objetivo cada vez que haya punto. Si lo pisas antes que nadie, el chat aplaude.", d: 1},
      {t: "Sobrevive a una pelea entera sin retroceder gracias solo a Sobrecarga cardíaca y di «esto me hace cosquillas».", d: 2}
    ] },
    { id: "orisa", name: "Orisa", role: "tank", subrole: "Fuerte", retos: [
      {t: "Cada Jabalina de energía tiene que empotrar a alguien contra una pared. Cada fallo: 3 flexiones.", d: 2},
      {t: "Aturde a un enemigo con la jabalina y remátalo antes de que se levante.", d: 2},
      {t: "Corazón de la tierra (ulti) cargado a tope: no puedes soltarlo antes del máximo nunca.", d: 2},
      {t: "Activa Fortificar solo cuando estés por debajo de la mitad de vida y avisa en voz alta «¡AGUANTANDO!».", d: 2},
      {t: "Pilla a 3 enemigos a la vez con Giro de jabalina empujándolos hacia atrás.", d: 3},
      {t: "Toda la partida sin dejar que el Aumentador fusión se sobrecaliente: suelta el gatillo antes de llegar al máximo.", d: 2},
      {t: "Cada vez que actives Fortificar, di «Fortificando, bleep bloop».", d: 1},
      {t: "Consigue una baja rematando con la jabalina a alguien que huye con poca vida.", d: 3},
      {t: "Juega como caballo: toda la partida cargando hacia el enemigo con Giro de jabalina en cada pelea.", d: 1},
      {t: "Protege a tu support con el Giro de jabalina, poniéndote delante de él al menos 3 veces en la partida.", d: 2},
      {t: "Tu ulti tiene que pillar mínimo a 3 enemigos. Si pilla menos, 10 sentadillas.", d: 2},
      {t: "Juega con la ventaja Heavy Javelin (mayor) siempre que salga y empotra a alguien con daño de pared.", d: 1},
      {t: "Al empezar cada ronda, haz el emote de Orisa delante de tu equipo y di «protocolo de defensa activado».", d: 1}
    ] },
    { id: "ramattra", name: "Ramattra", role: "tank", subrole: "Valeroso", retos: [
      {t: "Aniquilación tiene que durar al menos 10 segundos gracias a mantener enemigos dentro. El chat cronometra.", d: 3},
      {t: "Pon Vórtice voraz debajo del equipo enemigo y que tu equipo mate a alguien dentro del charco.", d: 2},
      {t: "Solo puedes pegar en Forma némesis cuando estés a menos de 5 metros. Nada de puñetazos al aire.", d: 2},
      {t: "Tras cada baja, di algo filosófico sobre los ómnicos y la humanidad con voz de profeta.", d: 1},
      {t: "Barrera del vacío solo para salvar a compañeros, nunca para ti mismo.", d: 2},
      {t: "Entra en Forma némesis con los brazos cruzados (bloqueo) y aguanta en primera línea hasta que se acabe.", d: 2},
      {t: "Prohibido usar el bastón en forma ómnica para matar: todas las bajas tienen que ser a puñetazos.", d: 2},
      {t: "Consigue que el vórtice mate a alguien directamente (remate con el vórtice).", d: 3},
      {t: "Bloquea con los brazos en Forma némesis un ulti enemigo y sobrevive. El chat lo valida.", d: 2},
      {t: "Cada vez que uses Forma némesis tienes que tararear algo épico.", d: 1},
      {t: "Aguanta la línea de frente entera sin retroceder durante la primera pelea de cada ronda.", d: 1},
      {t: "Consigue 3 bajas en una misma Forma némesis.", d: 3},
      {t: "Tras cada victoria de pelea, haz un spray en el objetivo y declara el punto «territorio del Sector Nulo».", d: 1}
    ] },
    { id: "reinhardt", name: "Reinhardt", role: "tank", subrole: "Valeroso", retos: [
      {t: "Cada vez que cargues con Carga, tienes que gritar el nombre del enemigo que te llevas. Si no lo empotras contra una pared, 5 flexiones al acabar.", d: 2},
      {t: "Seísmo tiene que tumbar a 3 o más enemigos. Si tumba a menos, el chat elige la próxima ventaja.", d: 3},
      {t: "Grita «¡HAMMER DOWN!» o «¡TIERRA, TIEMBLA!» en cada Seísmo, a la vez que la voz del juego.", d: 1},
      {t: "Prohibido levantar la barrera más de 3 segundos seguidos. Rein agresivo de verdad.", d: 2},
      {t: "Antes de cada pelea, golpea el suelo con el martillo mirando al enemigo y usa la línea de voz de reto. Duelo de honor.", d: 1},
      {t: "Gana el 1v1 contra el tanque enemigo sin levantar la barrera.", d: 3},
      {t: "Golpe de fuego doble: pilla a 2 enemigos con el mismo Golpe de fuego, 3 veces en la partida.", d: 2},
      {t: "Todo lo que digas por el micro tiene que ser en tono caballeresco y medieval, llamando «honor» a todo.", d: 1},
      {t: "Cancela una Carga a mitad de camino para no pasarte de largo y sigue pegando. El chat decide si fue limpio.", d: 2},
      {t: "Barrera solo para cubrir a tus supports: si la levantas sin ningún support detrás, bebe agua.", d: 2},
      {t: "Mata a un support enemigo con el martillo en su backline.", d: 2},
      {t: "Tras cada Seísmo que no tumbe a nadie, di «perdonad, estoy mayor».", d: 1},
      {t: "Consigue un Seísmo + Carga al mismo enemigo tumbado para matarlo.", d: 2}
    ] },
    { id: "roadhog", name: "Roadhog", role: "tank", subrole: "Fuerte", retos: [
      {t: "Cada gancho tiene que traer a alguien a su muerte. Gancho fallado: 3 flexiones.", d: 2},
      {t: "Engancha a un support enemigo y mátalo antes de que tu equipo le toque.", d: 3},
      {t: "Engancha a un enemigo mientras tú estás en el aire (salta antes del gancho). Tres veces en la partida.", d: 3},
      {t: "Toda la partida sin usar el respiro (curación) delante de un enemigo: solo te curas detrás de una esquina.", d: 2},
      {t: "Tras cada gancho acertado, di «¡VEN AQUÍ!» por el micro.", d: 1},
      {t: "Tu ulti tiene que echar a 2 enemigos del objetivo o matar a uno.", d: 2},
      {t: "Juega como cerdo solitario: flanquea y engancha desde un lado en cada pelea, nunca desde el frente.", d: 2},
      {t: "Engancha a alguien desde más lejos que tu equipo entero y tráelo hasta ellos.", d: 3},
      {t: "Cada Pig Pen tiene que colocarse justo en la salida del spawn enemigo o en un pasillo de flanqueo, y tiene que atrapar a alguien.", d: 2},
      {t: "Engancha al mismo enemigo 3 veces en la partida y dile algo cariñoso por el chat de texto.", d: 1},
      {t: "Salva a un aliado enganchando al enemigo que lo está rematando.", d: 2},
      {t: "Después de cada baja con gancho, haz un spray de cerdito o el más feo que tengas en el sitio del crimen.", d: 1}
    ] },
    { id: "sigma", name: "Sigma", role: "tank", subrole: "Valeroso", retos: [
      {t: "Flujo gravitatorio tiene que levantar a 3 o más enemigos. Si levanta menos, 10 sentadillas.", d: 3},
      {t: "Consigue una baja con Acreción contra un enemigo que esté en el aire (saltando, volando o cayendo).", d: 2},
      {t: "Trágate con Agarre cinético el Barrage de una Pharah enemiga. Si no hay Pharah, cualquier ulti de proyectiles; el chat lo valida.", d: 3},
      {t: "Cada vez que uses Agarre cinético, tararea una melodía. Sigma adora la música de las esferas.", d: 1},
      {t: "Deja caer a todos los atrapados por Flujo gravitatorio y remata a uno con Acreción antes de que se levante.", d: 3},
      {t: "Solo puedes lanzar la Barrera experimental más allá de la mitad del camino entre tu equipo y el enemigo: barrera ofensiva.", d: 2},
      {t: "Toda la partida hablando como un científico despistado que habla con el universo.", d: 1},
      {t: "Consigue una baja rematando con Acreción.", d: 2},
      {t: "Prohibido recuperar la barrera antes de que se rompa: una vez lanzada, se queda donde está.", d: 2},
      {t: "Consigue una baja con las Hiperesferas rebotando en una pared, sin línea de visión directa.", d: 3},
      {t: "Antes de cada pelea, flota un momento mirando al cielo y di «el universo canta». Luego al lío.", d: 1},
      {t: "Cada Acreción que falle: bebe agua.", d: 1}
    ] },
    { id: "winston", name: "Winston", role: "tank", subrole: "Iniciador", retos: [
      {t: "Cada Salto propulsado tiene que caer encima de la backline enemiga, nunca en el frente.", d: 2},
      {t: "Con Rabia primigenia, empuja a 3 enemigos distintos lejos del objetivo.", d: 3},
      {t: "Grita «¿Crema de cacahuete?» cada vez que actives Rabia primigenia.", d: 1},
      {t: "Cuando mates a alguien, dile algo de ciencia por el chat de texto.", d: 1},
      {t: "Mata con el cañón tesla a un enemigo de mucha movilidad (Tracer, Genji, Sombra…) sin que se te escape.", d: 2},
      {t: "Tu barrera tiene que caer encima de un aliado en peligro al menos 3 veces en la partida para salvarle.", d: 2},
      {t: "Toda la partida sin usar el disparo cargado secundario del cañón tesla: solo el chorro de electricidad.", d: 2},
      {t: "Dive en solitario a un support enemigo y mátalo sin ayuda.", d: 3},
      {t: "Durante Rabia primigenia, tira a un enemigo al vacío.", d: 3},
      {t: "Tras cada salto, pon la barrera en el sitio donde aterrizas antes de disparar. Siempre, sin excepción.", d: 2},
      {t: "Toda la partida tienes que saltar sobre el enemigo al menos una vez por cada respawn.", d: 1},
      {t: "Entra, mata, y vuelve con salto a tu equipo sin morir: 3 veces en la partida.", d: 3}
    ] },
    { id: "wrecking-ball", name: "Wrecking Ball", role: "tank", subrole: "Iniciador", retos: [
      {t: "Cada Machaque (Piledriver) tiene que levantar a 2 o más enemigos. Si solo pilla a uno, 5 flexiones.", d: 2},
      {t: "Tira a un enemigo al vacío de un choque con la bola.", d: 3},
      {t: "Campo de minas tiene que conseguir al menos una baja.", d: 2},
      {t: "Pasa toda la partida en modo bola salvo para disparar: si te quedas en modo hámster más de 5 segundos, bebe agua.", d: 2},
      {t: "Cada vez que mueras, di «Hammond está triste» con voz de hámster.", d: 1},
      {t: "Usa el garfio para dar vueltas alrededor de un poste y derribar a 3 enemigos del tirón.", d: 3},
      {t: "Entre peleas, haz una ronda por los packs de vida del lado enemigo del mapa y cógelos todos aunque vayas a tope de vida.", d: 1},
      {t: "Consigue que Escudos adaptativos te salve en medio del equipo enemigo y sal vivo.", d: 2},
      {t: "Prohibido tocar el objetivo en tu primera vida: tienes que molestar a la backline antes.", d: 2},
      {t: "Machaque encima de un support enemigo y remátalo antes de que se levante.", d: 3},
      {t: "Tu Campo de minas tiene que caer siempre encima del objetivo (punto o carga), nunca en otro sitio.", d: 2},
      {t: "Cada vez que hagas un gran rebote sin garfio, di «¡BOING!»", d: 1}
    ] },
    { id: "zarya", name: "Zarya", role: "tank", subrole: "Fuerte", retos: [
      {t: "Bomba de gravitones tiene que pillar a 3 o más enemigos. Si pilla menos, 10 sentadillas.", d: 3},
      {t: "Consigue la energía al 100% al menos 3 veces en la partida. Grita «¡CIEN!» cada vez.", d: 2},
      {t: "Solo puedes dar la Barrera proyectada a quien esté a punto de morir: cada una tiene que salvar una vida.", d: 2},
      {t: "Tras cada Barrera de partículas, di algo motivador en ruso de mentira.", d: 1},
      {t: "Consigue que tu equipo mate a 2 o más enemigos dentro de tu Bomba de gravitones.", d: 3},
      {t: "Prohibido usar el disparo secundario (bolas): solo el rayo.", d: 2},
      {t: "Cada vez que ganéis una pelea, haz el emote de flexionar músculos o de pesas en el objetivo.", d: 1},
      {t: "Consigue una baja con las bolas del disparo secundario rebotando en el suelo, sin usar el rayo.", d: 2},
      {t: "Cada burbuja que caduque sin absorber nada: bebe agua.", d: 1},
      {t: "Gana el 1v1 contra el tanque enemigo a alta energía.", d: 3},
      {t: "Toda la partida hablando de pesas y de levantar más peso que el enemigo.", d: 1},
      {t: "Antes de cada Bomba de gravitones, avisa al equipo con un ping y una cuenta atrás de 3 por el micro. Sin cuenta atrás, no hay bomba.", d: 2}
    ] },
    { id: "anran", name: "Anran", role: "damage", subrole: "Flanqueador", retos: [
      {t: "Cada baja tiene que ser de un enemigo que esté ardiendo por tu pasiva Ignición. Si matas a alguien sin quemar, no cuenta.", d: 2},
      {t: "Usa Vermillion Revival para volver de la muerte y consigue una baja en los 5 segundos siguientes.", d: 3},
      {t: "Mete Dancing Blaze en mitad del equipo enemigo, esquiva todo y sal viva con al menos una baja.", d: 3},
      {t: "Cada Inferno Rush tiene que chocar contra un enemigo. Rush al aire: 3 flexiones.", d: 2},
      {t: "Grita «¡FUEGO!» cada vez que uses Fan the Flames para rematar.", d: 1},
      {t: "Vermillion Ascent tiene que prender a 3 enemigos o más a la vez.", d: 3},
      {t: "Juega con abanicos de verdad: prohibido disparar desde más de 15 metros.", d: 2},
      {t: "Guarda el ulti para usarlo muerta: toda la partida solo puedes usar Vermillion Revival, nunca Ascent.", d: 2},
      {t: "Quema a todo el equipo enemigo a la vez al menos una vez en la partida (5 enemigos ardiendo).", d: 3},
      {t: "Aprovecha la pasiva Flanqueador: cada vez que vayas a por un pack de vida, dilo en voz alta y di cuánto te ha curado.", d: 1},
      {t: "Remata con Inferno Rush a un enemigo que huye con poca vida.", d: 2},
      {t: "Tras cada baja, haz una pose con el emote o spray. Estilo de bailarina de fuego.", d: 1}
    ] },
    { id: "ashe", name: "Ashe", role: "damage", subrole: "En el blanco", retos: [
      {t: "Cada dinamita tiene que explotar de un disparo en el aire, nunca al tocar el suelo. Dinamita que cae sola: 3 sentadillas.", d: 2},
      {t: "Bob tiene que conseguir una baja por su cuenta en cada invocación.", d: 2},
      {t: "Usa la Escopeta para empujar a un enemigo y remátalo en el aire antes de que caiga.", d: 3},
      {t: "Solo puedes disparar sin apuntar (desde la cadera). Prohibido el zoom toda la partida.", d: 3},
      {t: "Cada vez que actives a Bob grita «¡BOB, HAZ ALGO!» a la vez que Ashe.", d: 1},
      {t: "Cada vez que Bob termine su carga, ponte a su lado y haz un emote juntos antes de que desaparezca.", d: 1},
      {t: "Usa la Escopeta solo para subir a posiciones altas, nunca para escapar hacia atrás.", d: 2},
      {t: "Bob tiene que cargar al menos 3 enemigos y derribarlos.", d: 3},
      {t: "Remata a alguien quemado por la dinamita con un tiro a la cabeza con zoom.", d: 2},
      {t: "Toda la partida hablando como jefa de banda de Deadlock: cada muerte de tu equipo es «un inútil menos».", d: 1},
      {t: "Consigue 3 tiros a la cabeza seguidos con zoom sin fallar ninguno.", d: 3},
      {t: "Tras cada baja con zoom, haz un emote o una línea de voz antes de volver a apuntar.", d: 1}
    ] },
    { id: "bastion", name: "Bastion", role: "damage", subrole: "Especialista", retos: [
      {t: "Solo puedes activar la Configuración: Asalto cuando al menos 3 enemigos estén a la vista.", d: 2},
      {t: "Cada Configuración: Artillería tiene que conseguir mínimo una baja. Si no, 5 flexiones.", d: 2},
      {t: "Usa la granada táctica A-36 para hacer rocket jump y llegar a una posición alta. Tres veces en la partida.", d: 1},
      {t: "Tras cada baja, di un «bip-bup» emocionado por el micro.", d: 1},
      {t: "Gana un 1v1 solo con el modo reconocimiento, sin transformarte.", d: 2},
      {t: "Tu artillería tiene que caer encima de al menos 2 enemigos a la vez.", d: 3},
      {t: "Prohibido transformarte en el objetivo: solo en torres o flancos.", d: 2},
      {t: "Consigue 3 bajas en una sola Configuración: Asalto.", d: 3},
      {t: "Toda la partida sin tocar la granada. Solo pium pium.", d: 1},
      {t: "Al respawnear, busca un pájaro, planta o flor del mapa y quédate mirándolo 3 segundos antes de ir a la pelea.", d: 1},
      {t: "Consigue una baja con la granada rebotando en una pared.", d: 2},
      {t: "Mata con la granada a alguien que va huyendo con poca vida.", d: 2}
    ] },
    { id: "cassidy", name: "Cassidy", role: "damage", subrole: "En el blanco", retos: [
      {t: "Grita «Es mediodía...» antes de cada Dead Eye. Si Dead Eye no mata a nadie, 10 flexiones.", d: 2},
      {t: "Solo puedes matar con el revólver apuntando: prohibido Abanico del martillo para rematar.", d: 2},
      {t: "Aturde con Flashbang a un enemigo a menos de 5 metros y remátalo con un disparo a la cabeza.", d: 2},
      {t: "Dead Eye tiene que matar al menos a 2 enemigos a la vez.", d: 3},
      {t: "Toda la partida con acento de vaquero: «forastero», «partner» y «ajá» en cada frase.", d: 1},
      {t: "Antes de cada duelo, ponle un spray a tu rival a los pies y dale 3 segundos de cortesía antes de disparar. Duelo del Oeste.", d: 3},
      {t: "Cada vez que ganes un 1v1, pon un spray sobre el cadáver como cartel de «Se busca» y anuncia la recompensa por el micro.", d: 1},
      {t: "Prohibido rodar hacia atrás: solo puedes rodar de lado o hacia delante.", d: 2},
      {t: "Consigue un cargador entero sin fallar un solo tiro (6 de 6).", d: 3},
      {t: "Cada vez que mueras, di «esta ciudad no es lo bastante grande para los dos».", d: 1},
      {t: "Aguanta en un ángulo con buena línea de visión toda la primera pelea de cada ronda sin moverte de él.", d: 1},
      {t: "Usa el ulti solo para obligar a los enemigos a esconderse y que tu equipo tome el punto.", d: 2}
    ] },
    { id: "echo", name: "Echo", role: "damage", subrole: "Reconocimiento", retos: [
      {t: "Duplica al tanque enemigo y consigue una baja con su ulti.", d: 2},
      {t: "Duplica a un support enemigo y usa su ulti para ganar la pelea.", d: 2},
      {t: "Vuela con Vuelo hacia un enemigo y remátalo con el golpe cuerpo a cuerpo al llegar.", d: 2},
      {t: "Cada Rayo concentrado tiene que rematar a alguien por debajo de la mitad de vida.", d: 2},
      {t: "Consigue una baja con Rayo concentrado sin tocar el suelo desde que saliste del spawn.", d: 3},
      {t: "Duplica y consigue 3 bajas o más con el ulti copiado.", d: 3},
      {t: "Tras cada Duplicar, habla como el héroe que has copiado hasta que se acabe.", d: 1},
      {t: "Solo puedes usar Vuelo para entrar, nunca para huir.", d: 2},
      {t: "Consigue que las Bombas adhesivas maten a dos a la vez.", d: 2},
      {t: "Planea desde lo más alto del mapa hasta el objetivo sin tocar el suelo.", d: 1},
      {t: "Duplica siempre al enemigo que más te ha matado. Dilo en voz alta antes de duplicar.", d: 2},
      {t: "Cada vez que duplicas, di «¡copiando!» y cómo te sientes en ese héroe.", d: 1}
    ] },
    { id: "emre", name: "Emre", role: "damage", subrole: "Especialista", retos: [
      {t: "Todas tus bajas tienen que ser con Siphon Blaster: el rifle solo sirve para bajar vida.", d: 2},
      {t: "Override Protocol tiene que conseguir mínimo 2 bajas. Si no, 10 sentadillas.", d: 3},
      {t: "Cada Cyber Frag tiene que rebotar al menos una vez en pared antes de pillar a alguien.", d: 2},
      {t: "Juega de run-and-gun: prohibido quedarte quieto más de 2 segundos seguidos disparando.", d: 2},
      {t: "Consigue 3 bajas seguidas aprovechando la recarga rápida de la pasiva Especialista sin recargar manual.", d: 3},
      {t: "Mata con Cyber Frag a alguien que huye con poca vida.", d: 2},
      {t: "Tras cada baja, di «protocolo completado» con voz de ciborg.", d: 1},
      {t: "Usa Take Aim en todos los disparos del rifle: toda la partida con zoom.", d: 2},
      {t: "Recupera vida con Siphon Blaster y sobrevive a un 1v1 que parecía perdido.", d: 2},
      {t: "Gana un duelo a larga distancia usando solo Take Aim y ráfagas del Synthetic Burst Rifle.", d: 3},
      {t: "Cada vez que tu pasiva Altered Vitals te salve, di «otra vez de vuelta».", d: 1},
      {t: "Override Protocol: mata a alguien solo con los megadisparos cargados.", d: 2}
    ] },
    { id: "freja", name: "Freja", role: "damage", subrole: "Reconocimiento", retos: [
      {t: "Cada Quick Dash tiene que acabar con un disparo de ballesta acertado. Dash sin impacto: 3 flexiones.", d: 2},
      {t: "Encadena Updraft + Take Aim + Quick Dash en el aire y consigue una baja sin tocar el suelo.", d: 3},
      {t: "Usa Take Aim en el aire en cada disparo: prohibido disparar desde el suelo.", d: 2},
      {t: "Tu Bola Shot (ulti) tiene que pillar a 2 o más enemigos.", d: 3},
      {t: "Tras cada baja, di el nombre de la presa como si estuvieras cazando.", d: 1},
      {t: "Usa Updraft para esquivar una muerte segura y remata al que te estaba disparando.", d: 3},
      {t: "Consigue 3 bajas encadenadas usando Quick Dash para recargar ballesta.", d: 3},
      {t: "Solo puedes cazar supports: prohibido disparar a tanques.", d: 2},
      {t: "Toda la partida como cazarrecompensas danesa: cada kill es «dinero en el banco».", d: 1},
      {t: "Aprovecha la pasiva de Reconocimiento: avisa al equipo en voz alta de cada enemigo a media vida que ves tras muros.", d: 1},
      {t: "Tras cada baja, marca el cadáver con un ping y un spray: tu trofeo de caza.", d: 1},
      {t: "Consigue un doble kill con una sola ráfaga de ballesta.", d: 3}
    ] },
    { id: "genji", name: "Genji", role: "damage", subrole: "Flanqueador", retos: [
      {t: "Grita «¡Ryujin no ken wo kurae!» cada vez que saques Dragonblade. Si no matas a nadie con ella, 10 flexiones.", d: 2},
      {t: "Mata a alguien con un proyectil devuelto con Desviar.", d: 3},
      {t: "Dragonblade: mínimo 3 bajas por ulti.", d: 3},
      {t: "Toda la partida sin usar el disparo principal: solo abanico de shurikens y melé.", d: 2},
      {t: "Cada Golpe veloz tiene que rematar a alguien. Dash sin kill: bebe agua.", d: 2},
      {t: "Pide curación a los supports con «¡Necesito curación!» cada 10 segundos durante la primera ronda. El meme vive.", d: 1},
      {t: "Antes de entrar a por un objetivo, ponle un spray a sus pies y hazle una reverencia (agáchate dos veces). Honor ninja.", d: 2},
      {t: "Escala por paredes para flanquear cada vez que respawnees: prohibido entrar por la puerta principal.", d: 1},
      {t: "Consigue una baja con los tres shurikens del disparo principal directos a la cabeza.", d: 2},
      {t: "Antes de cada Dragonblade, pide nano o avisa al equipo por el micro. Sin anuncio, no hay espada.", d: 2},
      {t: "Consigue un reset de Golpe veloz dos veces seguidas en el mismo Dragonblade.", d: 2},
      {t: "Tras cada baja, haz una reverencia (emote o agacharte tres veces).", d: 1}
    ] },
    { id: "hanzo", name: "Hanzo", role: "damage", subrole: "En el blanco", retos: [
      {t: "Una flecha, un headshot: tienes que conseguir mínimo 3 kills de un solo tiro a la cabeza.", d: 3},
      {t: "Grita «¡Ryuu ga waga teki wo kurau!» en cada Golpe del dragón. Si no mata a nadie, 10 flexiones.", d: 2},
      {t: "Usa Flecha sónica antes de cada pelea y avisa por el micro de cuántos enemigos ves.", d: 1},
      {t: "Solo puedes disparar flechas cargadas al máximo. Nada de spam.", d: 2},
      {t: "Consigue una kill con una flecha lanzada «al azar» contra un grupo (sin apuntar a nadie). El chat lo juzga.", d: 1},
      {t: "Tras cada headshot, haz un spray en tu posición y cambia de sitio antes del siguiente tiro.", d: 2},
      {t: "Encadena Salto y Escalada para llegar a una posición que ningún aliado haya pisado en toda la partida.", d: 2},
      {t: "Toda la partida en la misma posición alta: prohibido bajar al suelo salvo al morir.", d: 2},
      {t: "Flechas de tormenta: mata a un tanque con una sola ráfaga.", d: 3},
      {t: "Cada vez que hagas una kill de chiripa, di «pura habilidad» con toda la seriedad.", d: 1},
      {t: "Tu Golpe del dragón tiene que atravesar a 3 enemigos o más.", d: 2},
      {t: "Consigue una baja con una flecha disparada en pleno Salto (Lunge). Clip o no pasó.", d: 3}
    ] },
    { id: "junkrat", name: "Junkrat", role: "damage", subrole: "Especialista", retos: [
      {t: "Solo puedes matar con la trampa + otro golpe; cada kill tiene que empezar con alguien atrapado.", d: 3},
      {t: "Grita «¡FIRE IN THE HOLE!» con cada Rip-Tire. Si no mata a nadie, 10 flexiones.", d: 2},
      {t: "Usa la Mina de conmoción para hacer un salto doble hasta la backline enemiga.", d: 2},
      {t: "Mata a alguien con el impacto directo de la Mina de conmoción.", d: 3},
      {t: "Rip-Tire subiendo por una pared hasta un enemigo que se cree a salvo.", d: 2},
      {t: "Cuando mueras, tus granadas de muerte tienen que matar a alguien una vez en la partida.", d: 3},
      {t: "Toda la partida riendo como un loco cada vez que explota algo. El chat decide si la risa vale.", d: 1},
      {t: "Prohibido disparar granadas directas: solo rebotes en paredes.", d: 2},
      {t: "Pon la trampa en el pack de vida enemigo y atrapa a alguien que vaya a curarse.", d: 1},
      {t: "Consigue 3 kills con un solo Rip-Tire.", d: 3},
      {t: "Cada trampa que no atrape a nadie en toda su vida útil: bebe agua.", d: 1},
      {t: "Spam de pasillo: dispara granadas a cada esquina antes de asomarte. Nunca asomes sin haber lanzado antes.", d: 1}
    ] },
    { id: "mei", name: "Mei", role: "damage", subrole: "Especialista", retos: [
      {t: "Usa Muro de hielo para dividir al equipo enemigo y consigue una kill al que se quede solo.", d: 2},
      {t: "Levanta a un enemigo con el Muro de hielo desde abajo y remátalo cuando caiga.", d: 3},
      {t: "Ventisca tiene que congelar o ralentizar a 3 o más enemigos.", d: 3},
      {t: "Pon el muro para cortar la línea de visión del equipo enemigo justo cuando tu equipo entra a pelear.", d: 2},
      {t: "Levanta el muro para subirte tú a una posición alta tres veces en la partida.", d: 1},
      {t: "Cada vez que uses Criocongelación di «¡A-Mei-zing!» con voz alegre.", d: 1},
      {t: "Aísla a un support enemigo con el muro y mátalo.", d: 2},
      {t: "Solo puedes usar el disparo secundario (carámbano) para matar.", d: 2},
      {t: "Toda la partida hablando de clima y de salvar el planeta cuando mueras.", d: 1},
      {t: "Tras cada baja, construye un pilar de hielo sobre el cadáver y haz un spray delante: monumento a la víctima.", d: 1},
      {t: "Tu Ventisca tiene que caer siempre encima del objetivo, nunca en otro sitio, y di «¡a congelarse!» al lanzarla.", d: 2},
      {t: "Prohibido usar el muro para escapar: solo ofensivo o para aliados.", d: 2}
    ] },
    { id: "pharah", name: "Pharah", role: "damage", subrole: "Reconocimiento", retos: [
      {t: "Toda la partida en el aire: si tocas el suelo más de 3 segundos seguidos, 3 flexiones.", d: 2},
      {t: "Grita «¡La justicia llueve desde arriba!» en cada Barrage. Si no mata a nadie, 10 flexiones.", d: 2},
      {t: "Aprovecha las Drift Thrusters: Barrage moviéndote para rodear una esquina y matar a 2.", d: 3},
      {t: "Empuja a un enemigo con Disparo de conmoción y remátalo con un cohete directo en el aire.", d: 3},
      {t: "Consigue 3 impactos directos de cohete seguidos.", d: 2},
      {t: "Cada vez que un support aliado te cure en el aire, dale las gracias con la línea de voz «Gracias».", d: 1},
      {t: "Consigue una baja desde más alto que cualquier edificio del mapa.", d: 3},
      {t: "Prohibido tocar el objetivo a pie: solo puedes contestarlo volando.", d: 2},
      {t: "Usa Disparo de conmoción para separar a un tanque de su equipo.", d: 2},
      {t: "Cada vez que te bajen del cielo, di el nombre de quien te ha matado con rabia y promete venganza.", d: 1},
      {t: "Mata con cohetes a alguien que esté detrás de una esquina rebotando la explosión.", d: 2},
      {t: "Barrage desde el cielo al centro del objetivo, sin cobertura, y sobrevive.", d: 3}
    ] },
    { id: "reaper", name: "Reaper", role: "damage", subrole: "Flanqueador", retos: [
      {t: "Grita «¡MORID, MORID, MORID!» en cada Flor de la muerte. Si no mata a nadie, 10 flexiones.", d: 2},
      {t: "Usa Paso de las sombras para colocarte detrás de la backline enemiga en cada respawn.", d: 2},
      {t: "Toda la partida sin usar Forma espectral.", d: 2},
      {t: "Flor de la muerte: 3 o más kills en un solo ulti.", d: 3},
      {t: "Mata a un tanque en solitario de un cara a cara.", d: 2},
      {t: "Usa Dire Triggers solo para rematar a enemigos que huyen.", d: 1},
      {t: "Antes de cada Paso de las sombras, pon un spray en el sitio de destino con un ping para avisar. Terror anunciado.", d: 2},
      {t: "Toda la partida hablando con voz grave y dramática sobre Gabriel Reyes y tus traiciones.", d: 1},
      {t: "Prohibido disparar desde más de 10 metros salvo con Dire Triggers.", d: 2},
      {t: "Mata al que esté en la posición más alta del equipo enemigo apareciendo detrás de él con Paso de las sombras.", d: 3},
      {t: "Cada vez que mueras, di «...edgy» con toda la depresión que puedas.", d: 1},
      {t: "Aprovecha los packs de vida: después de cada pelea, pasa por uno antes de volver y di cuánto te cura.", d: 1}
    ] },
    { id: "shion", name: "Shion", role: "damage", subrole: "Flanqueador", retos: [
      {t: "Cada Joyride tiene que acabar con la moto lanzada contra un enemigo. Moto al aire: 5 flexiones.", d: 2},
      {t: "Satsuriku Spree tiene que matar a 2 enemigos o más en las tres acometidas.", d: 3},
      {t: "Carga Execution al máximo (cruz cerrada) y mata a alguien con ella.", d: 2},
      {t: "Usa Evade justo cuando te vayan a matar para sobrevivir con la sobrevida.", d: 2},
      {t: "Prohibido bajarte de la moto antes de estar en el flanco enemigo.", d: 2},
      {t: "Grita «¡BRUM BRUM!» cada vez que arranques Joyride.", d: 1},
      {t: "Mata a un support enemigo llegando en moto.", d: 2},
      {t: "Cada vez que desbloquees una ventaja, la elige el chat. Sin quejarse.", d: 1},
      {t: "Consigue 3 kills sin recargar gracias a la ventaja Rapid Reload.", d: 3},
      {t: "Atropella a un enemigo lanzando la moto y mátalo antes de que se levante.", d: 2},
      {t: "Tras cada baja, dedica una frase de yakuza a tu víctima.", d: 1},
      {t: "Satsuriku Spree para rodear al tanque enemigo y matar a un support.", d: 3}
    ] },
    { id: "sierra", name: "Sierra", role: "damage", subrole: "Reconocimiento", retos: [
      {t: "Cada vez que marques a alguien con Tracking Shot, dispárale hasta que muera o se esconda. Nada de cambiar de objetivo.", d: 2},
      {t: "Usa Anchor Drone para subir a una posición alta en cada respawn.", d: 1},
      {t: "Tremor Charge tiene que golpear a 2 o más enemigos a la vez.", d: 2},
      {t: "Trailblazer tiene que matar al menos a 2 enemigos.", d: 3},
      {t: "Consigue una baja disparando mientras vuelas hacia tu Anchor Drone.", d: 2},
      {t: "Prohibido disparar sin haber marcado primero con Tracking Shot.", d: 2},
      {t: "Aprovecha la pasiva de Reconocimiento: canta por el micro cada enemigo revelado a media vida.", d: 1},
      {t: "Lanza el Anchor Drone, pelea lejos de él y vuelve con él justo cuando estés a punto de morir. Tres veces en la partida.", d: 3},
      {t: "Con la ventaja Medi-Drone, cura a un aliado con el dron.", d: 1},
      {t: "Grita «¡OBJETIVO FIJADO!» cada vez que marques.", d: 1},
      {t: "Consigue 3 bajas con la hélice sin soltar el gatillo ni recargar.", d: 3},
      {t: "Tras cada baja, haz un spray en tu posición antes de lanzar el dron a la siguiente: exploradora que deja rastro.", d: 2}
    ] },
    { id: "sojourn", name: "Sojourn", role: "damage", subrole: "En el blanco", retos: [
      {t: "Mata a 3 enemigos con Railgun cargada a tope a la cabeza.", d: 3},
      {t: "Toda la partida deslizando: si no usas Carrera energizada con salto al menos una vez por pelea, 3 sentadillas.", d: 1},
      {t: "Sobrecarga: consigue 3 kills durante el ulti.", d: 3},
      {t: "Usa Disrupción para echar a los enemigos del objetivo.", d: 2},
      {t: "Prohibido disparar el Railgun sin carga completa.", d: 2},
      {t: "Consigue una baja con Railgun cargada en pleno salto de Carrera energizada.", d: 3},
      {t: "Desliza y salta sobre la cabeza de un enemigo, mátalo y sal vivo.", d: 2},
      {t: "Tras cada kill cargada, di «railgun, baby».", d: 1},
      {t: "Aprovecha la pasiva: cada crit reduce el cooldown de la carrera. Encadena tres carreras seguidas en una pelea.", d: 3},
      {t: "Mata de un railgun cargado a un enemigo a más de 30 metros.", d: 3},
      {t: "Toda la partida en posiciones altas a las que solo llegas con Carrera energizada.", d: 2},
      {t: "Cada railgun fallado con carga completa: bebe agua.", d: 1}
    ] },
    { id: "soldier-76", name: "Soldado: 76", role: "damage", subrole: "Especialista", retos: [
      {t: "Grita «¡Te tengo en la mira!» en cada Visor táctico. Si no mata a nadie, 10 flexiones.", d: 2},
      {t: "Tu Campo biótico tiene que salvar a un aliado de morir.", d: 1},
      {t: "Mata a alguien con el Cohete hélice directo.", d: 1},
      {t: "Usa el Cohete hélice para hacer rocket jump a una posición alta tres veces.", d: 2},
      {t: "Toda la partida corriendo con Sprint: prohibido andar si no estás disparando.", d: 1},
      {t: "Visor táctico: 3 kills o más.", d: 3},
      {t: "Consigue una baja disparando el rifle en pleno rocket jump con el Cohete hélice.", d: 3},
      {t: "Toda la partida hablando como un viejo militar gruñón que odia a los jóvenes.", d: 1},
      {t: "Prohibido usar el Campo biótico para ti solo: solo si hay un aliado cerca.", d: 2},
      {t: "Mata a un enemigo a más de 40 metros con ráfagas del rifle.", d: 3},
      {t: "Tras cada baja, suelta el Campo biótico sobre el cadáver y haz el saludo militar (emote o voz) antes de seguir.", d: 2},
      {t: "Gana un 1v1 a menos de 10 metros usando solo el rifle, sin cohete ni campo biótico.", d: 3}
    ] },
    { id: "sombra", name: "Sombra", role: "damage", subrole: "Reconocimiento", retos: [
      {t: "Hackea a un support enemigo y mátalo antes de que termine el efecto.", d: 2},
      {t: "IEM tiene que pillar a 3 o más enemigos.", d: 3},
      {t: "Cada vez que hackees un pack de vida, di «¡ESTE ES MÍO!»", d: 1},
      {t: "Usa Translocador para escapar justo a tiempo de una muerte segura.", d: 2},
      {t: "Prohibido usar el Virus: solo metralleta y hackeo.", d: 2},
      {t: "Antes de atacar a tu objetivo, sal de invisible, ponle un spray a los pies y salúdalo con «Hola». Luego, hackeo.", d: 3},
      {t: "Toda la partida hablando como hacker mexicana, con un «¿qué onda?» cada vez que hackees a alguien.", d: 1},
      {t: "Hackea al enemigo que esté en la posición más alta y mátalo.", d: 2},
      {t: "Lanza IEM y consigue que tu equipo mate a 3 o más enemigos en los 5 segundos siguientes.", d: 3},
      {t: "Consigue 3 bajas seguidas sin que te detecten.", d: 3},
      {t: "Aparece de invisible justo detrás del objetivo y di «boop» por el micro antes del primer disparo. Si te ven antes, no vale.", d: 1},
      {t: "Hackea al tanque enemigo al inicio de cada pelea y avisa por el micro «¡tanque hackeado!».", d: 2}
    ] },
    { id: "symmetra", name: "Symmetra", role: "damage", subrole: "Especialista", retos: [
      {t: "Coloca un teleportador que use al menos 3 aliados en una pelea.", d: 2},
      {t: "Tus torretas centinela tienen que conseguir una kill por sí solas.", d: 2},
      {t: "Tu Barrera fotónica tiene que cortar el mapa justo cuando tu equipo entra a pelear y aguantar toda la pelea.", d: 3},
      {t: "Toda la partida con el rayo principal: prohibido el orbe secundario.", d: 2},
      {t: "Coloca el teleportador para que al menos 2 aliados lleguen a la pelea desde el spawn antes que el enemigo.", d: 3},
      {t: "Pon torretas en la salida del spawn enemigo o en su pack de vida.", d: 1},
      {t: "Cada vez que el rayo esté a potencia máxima, di «perfección».", d: 1},
      {t: "Carga el rayo al máximo con el tanque enemigo y mata a alguien de la backline con él.", d: 2},
      {t: "Usa el teleportador para salvarte de una muerte segura.", d: 3},
      {t: "Prohibido dejar el teleportador sin usar cuando esté disponible.", d: 1},
      {t: "Coloca las tres torretas en forma de triángulo perfecto en cada pelea. El chat juzga la simetría.", d: 2},
      {t: "Tras cada kill, di «orden» con voz autoritaria.", d: 1}
    ] },
    { id: "torbjorn", name: "Torbjörn", role: "damage", subrole: "Especialista", retos: [
      {t: "Tu torreta tiene que conseguir 3 kills en la partida.", d: 2},
      {t: "Tu Núcleo fundido tiene que cubrir el objetivo entero y que ningún enemigo lo pise mientras dura.", d: 3},
      {t: "Lanza la torreta a una posición absurda (techo, cornisa rara) y que mate a alguien.", d: 2},
      {t: "Toda la partida sin usar el disparo secundario.", d: 1},
      {t: "Grita «¡HAMMER TIME!» cada vez que repares la torreta.", d: 1},
      {t: "Sobrecarga para ganar un 1v1 contra un tanque.", d: 3},
      {t: "Tu torreta tiene que durar viva una pelea entera sin que la destruyan.", d: 2},
      {t: "Toda la partida quejándote de las máquinas y de los ómnicos con acento sueco inventado.", d: 1},
      {t: "Prohibido colocar la torreta en el objetivo: solo en flancos o torres.", d: 2},
      {t: "Mata a alguien con el martillo en melé.", d: 2},
      {t: "Núcleo fundido: 2 kills en un solo ulti.", d: 3},
      {t: "Cada vez que destrocen tu torreta, di «¡mi niña!» con pena.", d: 1}
    ] },
    { id: "tracer", name: "Tracer", role: "damage", subrole: "Flanqueador", retos: [
      {t: "Grita «¡Ahí va el paquete!» en cada Bomba de pulsos. Si no mata a nadie, 10 flexiones.", d: 2},
      {t: "Pega la bomba en el tanque enemigo y mata a alguien más con la explosión.", d: 3},
      {t: "Usa Regresión para escapar de una muerte segura y mata al que te perseguía.", d: 2},
      {t: "Toda la partida sin Regresión.", d: 3},
      {t: "Mata a los supports enemigos 3 veces en la partida.", d: 2},
      {t: "Pega la Bomba de pulsos a un enemigo que esté en el aire (saltando, volando o cayendo).", d: 3},
      {t: "Cada vez que mueras, di «¡el reino de Tracer ha acabado!» con drama.", d: 1},
      {t: "Prohibido estar frente a frente con el tanque enemigo más de 3 segundos.", d: 2},
      {t: "Consigue una baja con el golpe cuerpo a cuerpo justo después de vaciar el cargador.", d: 1},
      {t: "Mata al enemigo en la posición más alta del mapa subiendo hasta él.", d: 3},
      {t: "Toda la partida hablando con acento británico: «cheers, love» incluido.", d: 1},
      {t: "Aguanta 5 segundos en medio del equipo enemigo sin morir (Parpadeo y Regresión permitidos).", d: 2}
    ] },
    { id: "vendetta", name: "Vendetta", role: "damage", subrole: "Flanqueador", retos: [
      {t: "Consigue al menos una baja por pelea con el tajo pesado que cierra el combo.", d: 2},
      {t: "Sundering Blade cargado al máximo: mata a 2 enemigos con un solo tajo.", d: 3},
      {t: "Usa Soaring Slice para lanzar la espada y volar hasta la backline enemiga en cada respawn.", d: 2},
      {t: "Aguanta con Warding Stance en mitad del equipo enemigo hasta vaciar la energía y sal viva.", d: 3},
      {t: "Llega a 5 stacks de Onslaught antes de cada kill.", d: 2},
      {t: "Grita «¡VENDETTA!» cada vez que lances Sundering Blade.", d: 1},
      {t: "Consigue 3 kills con Projected Edge.", d: 2},
      {t: "Prohibido usar Whirlwind Dash para escapar.", d: 2},
      {t: "Mata a un support enemigo en su backline y vuelve viva con tu equipo.", d: 2},
      {t: "Toda la partida hablando como jefa de la mafia italiana. Cada kill es «un regalo de familia».", d: 1},
      {t: "Mata al tanque enemigo en 1v1.", d: 3},
      {t: "Cada vez que mueras, di «esto no ha terminado» con rabia de gladiadora.", d: 1}
    ] },
    { id: "venture", name: "Venture", role: "damage", subrole: "Flanqueador", retos: [
      {t: "Cada vez que salgas de Excavar, tienes que golpear a alguien. Emerger sin pillar: 3 flexiones.", d: 2},
      {t: "Tectonic Shock tiene que pillar a 3 o más enemigos.", d: 3},
      {t: "Excava justo cuando te vayan a matar y sobrevive.", d: 2},
      {t: "Tras cada kill, di un dato de paleontología o geología.", d: 1},
      {t: "Mata a un support enemigo saliendo del suelo bajo él.", d: 2},
      {t: "Prohibido usar Drill Dash para huir.", d: 2},
      {t: "Toda la partida bajo tierra entre peleas: cuando vuelves al frente, siempre excavando.", d: 1},
      {t: "Salta desde bajo tierra y mata a un enemigo mientras sigue en el aire.", d: 3},
      {t: "Consigue un doble kill con Tectonic Shock.", d: 3},
      {t: "Antes de excavar hacia tu objetivo, ponle un spray a sus pies y dile «¡voy a por tus fósiles!» por el micro.", d: 2},
      {t: "Grita «¡EUREKA!» cada vez que encuentres un pack de vida.", d: 1},
      {t: "Aprovecha los packs de vida: nunca vuelvas a la pelea sin pasar por uno.", d: 1}
    ] },
    { id: "widowmaker", name: "Widowmaker", role: "damage", subrole: "En el blanco", retos: [
      {t: "Prohibido el garfio para huir: solo puedes usarlo para llegar a una posición nueva.", d: 2},
      {t: "Consigue 3 tiros a la cabeza de un solo disparo.", d: 3},
      {t: "Cambia de posición después de cada kill: nunca dos kills desde el mismo sitio.", d: 2},
      {t: "Tras cada baja, haz un spray en tu posición y el emote de reírte antes de moverte al siguiente sitio.", d: 2},
      {t: "Usa Visor infrarrojo y avisa al equipo de todos los enemigos que ves.", d: 1},
      {t: "Toda la partida hablando francés de mentira: «oh là là» en cada headshot.", d: 1},
      {t: "Consigue un headshot con zoom mientras cuelgas del garfio a mitad de trayecto.", d: 3},
      {t: "Pon la Mina venenosa en el pack de vida o en el flanco y que pille a alguien.", d: 1},
      {t: "Prohibido disparar sin zoom: todo con mira.", d: 2},
      {t: "Consigue una baja a quemarropa con el fusil en automático (sin zoom) y celébrala con un emote.", d: 2},
      {t: "Cada headshot fallado a un objetivo quieto: bebe agua.", d: 1},
      {t: "Usa el garfio para cruzar el mapa y sorprender desde un ángulo nuevo en cada ronda.", d: 2}
    ] },
    { id: "ana", name: "Ana", role: "support", subrole: "Estratega", retos: [
      {t: "Solo puedes usar la granada biótica para anular curación, nunca para curar a tu equipo.", d: 2},
      {t: "Duerme a un enemigo y que tu equipo lo mate antes de que se despierte.", d: 2},
      {t: "Nanoestimulante solo al tanque. Grita el nombre del tanque cuando lo lances.", d: 1},
      {t: "Duerme a dos enemigos distintos en la misma pelea: uno al empezar y otro cuando vuelva el dardo.", d: 3},
      {t: "Duerme a un enemigo que esté a menos de 5 metros de ti y remátalo con un tiro a la cabeza.", d: 2},
      {t: "Prohibido hacer scope: toda la partida sin apuntar con mira, solo disparos desde la cadera.", d: 2},
      {t: "Cada Dardo somnífero fallado: una flexión.", d: 1},
      {t: "Toda la partida hablando como una abuela: «hijo, ¿has comido?» cada vez que cures al tanque.", d: 1},
      {t: "Granada biótica a 3 enemigos a la vez para cortarles la curación.", d: 2},
      {t: "Duerme a un enemigo a más de 25 metros de distancia. El chat decide si estaba lejos de verdad.", d: 3},
      {t: "Tras cada Nanoestimulante, di «¡Tú puedes, cariño!». Si tu aliado nanoestimulado no mata a nadie, bebe agua.", d: 1},
      {t: "Cada vez que duermas a alguien, acércate, ponle un spray al lado y dale las buenas noches por el micro. Si te matan, valió la pena.", d: 2},
      {t: "Prohibido moverte de tu posición de tiro hasta que te obliguen a salir.", d: 2}
    ] },
    { id: "baptiste", name: "Baptiste", role: "support", subrole: "Estratega", retos: [
      {t: "Campo de inmortalidad tiene que salvar a un aliado que iba a morir sí o sí. El chat decide.", d: 2},
      {t: "Tu Matriz amplificadora tiene que conseguir 2 kills del equipo o más.", d: 2},
      {t: "Usa Botas de exo para subir a posiciones altas cada vez que respawnees.", d: 1},
      {t: "Durante la primera ronda, prohibido el disparo principal: solo granadas, Explosión regenerativa y campo.", d: 2},
      {t: "Gana un 1v1 usando solo el rifle de tres balas, sin Explosión regenerativa ni campo.", d: 2},
      {t: "Tras cada Campo de inmortalidad, grita «¡NADIE MUERE HOY!»", d: 1},
      {t: "Coloca la Matriz amplificadora justo cuando un aliado lance su ulti (Barrage, Golpe del dragón, Dead Eye…) y que consiga una baja.", d: 3},
      {t: "Toda la partida en el aire con Botas de exo cada vez que haya una pelea: el chat cuenta los saltos.", d: 1},
      {t: "Cada aliado que salves con el Campo de inmortalidad recibe un «¡de nada, hermano!» por la línea de voz de «De nada».", d: 1},
      {t: "Consigue una kill con disparos a la cabeza atravesando la matriz.", d: 3},
      {t: "Cada Campo de inmortalidad que no salve a nadie: bebe agua.", d: 1},
      {t: "Consigue 3 bajas con el rifle en una misma vida sin dejar de curar.", d: 3}
    ] },
    { id: "brigitte", name: "Brigitte", role: "support", subrole: "Superviviente", retos: [
      {t: "Cada Golpe de escudo tiene que aturdir a alguien. Golpe al aire: 3 flexiones.", d: 2},
      {t: "Rally tiene que salvar una pelea: 3 aliados mínimo con escudos al activarla.", d: 2},
      {t: "Empuja a un enemigo con Latigazo y remátalo antes de que se recupere.", d: 2},
      {t: "Solo puedes curar pegando a enemigos (Inspirar). Paquetes de reparación prohibidos.", d: 2},
      {t: "Protege a tu otro support toda la partida: nunca te alejes más de 10 metros de él.", d: 1},
      {t: "Cada vez que tires un Paquete de reparación, di «¡entrega a domicilio!» con el nombre del aliado.", d: 1},
      {t: "Mata a un enemigo que ataque a tu otro support.", d: 2},
      {t: "Tira a un enemigo al vacío con Latigazo y grita «¡FUERA!».", d: 2},
      {t: "Aguanta con el escudo delante de tu equipo hasta que te lo rompan y sobrevive.", d: 3},
      {t: "Consigue 3 kills durante Rally.", d: 3},
      {t: "Toda la partida sin levantar el escudo: modo berserker.", d: 2},
      {t: "Cada vez que tu escudo se rompa, di «¡mi padre me hizo este escudo!»", d: 1}
    ] },
    { id: "illari", name: "Illari", role: "support", subrole: "Superviviente", retos: [
      {t: "Sol cautivo tiene que pillar a 3 enemigos o más.", d: 3},
      {t: "Tu Pilar sanador tiene que durar toda la pelea sin que lo rompan.", d: 2},
      {t: "Usa Estallido para escapar de una muerte segura y remata al que te estaba disparando.", d: 2},
      {t: "Consigue 3 kills con disparos cargados a la cabeza.", d: 3},
      {t: "Grita «¡EL SOL SIEMPRE SALE!» con cada Sol cautivo.", d: 1},
      {t: "Prohibido curar con el arma: solo el pilar puede curar.", d: 2},
      {t: "Pon el Pilar sanador en una posición absurda (techo, esquina escondida) que dure toda la ronda.", d: 2},
      {t: "Consigue una baja con disparo cargado en pleno Estallido.", d: 2},
      {t: "Tras cada kill, di algo sobre los inti y el sol.", d: 1},
      {t: "Cada vez que pongas el pilar, haz un spray al lado y bautízalo con el nombre que diga el chat.", d: 1},
      {t: "Sol cautivo sobre el tanque enemigo y que tu equipo lo remate.", d: 2},
      {t: "Prohibido estar cerca de tu pilar: siempre en posición de tiro lejos de él.", d: 2}
    ] },
    { id: "jetpack-cat", name: "Jetpack Cat", role: "support", subrole: "Estratega", retos: [
      {t: "Remolca a tu tanque con Lifeline justo al centro del equipo enemigo al empezar cada pelea.", d: 2},
      {t: "Catnapper tiene que atar a un support enemigo y llevártelo hasta tu equipo.", d: 3},
      {t: "Toda la partida volando: la pasiva lo permite, así que si tocas el suelo, bebe agua.", d: 1},
      {t: "Cada vez que actives Purr, maúlla por el micro. Maullido obligatorio.", d: 1},
      {t: "Salva a un aliado a punto de morir sacándolo de la pelea con Lifeline.", d: 2},
      {t: "Empuja con Purr a 3 enemigos a la vez.", d: 3},
      {t: "Prohibido transportar al mismo aliado dos veces seguidas.", d: 2},
      {t: "Transporta a un aliado de daño hasta una posición alta que no podría alcanzar solo.", d: 2},
      {t: "Mata a alguien con las Biotic Pawjectiles.", d: 2},
      {t: "Toda la partida hablando como un gato: todo lo que digas termina en «miau».", d: 1},
      {t: "Consigue una kill del equipo después de tu Catnapper.", d: 2},
      {t: "Aprovecha la pasiva Estratega: guarda carga de ulti extra y usa dos ultis seguidos en la misma pelea.", d: 3},
      {t: "Como buen gato, tira algo: rompe con disparos todos los objetos del decorado que veas en el spawn antes de salir.", d: 1}
    ] },
    { id: "juno", name: "Juno", role: "support", subrole: "Superviviente", retos: [
      {t: "Anillo hiperespacial tiene que pasar por delante de toda tu línea de ataque en cada pelea.", d: 2},
      {t: "Rayo orbital tiene que matar a 2 enemigos o más.", d: 3},
      {t: "Torpedos pulsares a 4 aliados a la vez.", d: 2},
      {t: "Toda la partida en el aire: si tocas el suelo más de 3 segundos, bebe agua.", d: 2},
      {t: "Grita «¡PARA MARTE!» con cada Rayo orbital.", d: 1},
      {t: "Consigue una baja con el Mediblaster mientras planeas.", d: 2},
      {t: "Usa Deslizamiento para salvarte de una muerte segura.", d: 2},
      {t: "Prohibido curar con el arma: solo torpedos y ulti.", d: 2},
      {t: "Tras cada kill, di algo de ciencia espacial.", d: 1},
      {t: "Pasa con el anillo hiperespacial a tu tanque justo cuando entra a la pelea.", d: 1},
      {t: "Consigue que el Rayo orbital salve a tu tanque de morir.", d: 2},
      {t: "Toda la partida hablando como astronauta: «houston, tenemos un problema» cada vez que te maten.", d: 1},
      {t: "Cada aliado que esquive la muerte gracias a tus torpedos recibe un saludo espacial con la línea de voz «Hola».", d: 1}
    ] },
    { id: "kiriko", name: "Kiriko", role: "support", subrole: "Médico", retos: [
      {t: "Protección Suzu tiene que salvar a un aliado que iba a morir. El chat lo valida.", d: 2},
      {t: "Usa Paso veloz para teletransportarte detrás de una pared y salvarte de una muerte segura.", d: 2},
      {t: "Kitsune Rush tiene que empujar a tu equipo a ganar la pelea.", d: 2},
      {t: "Consigue 3 kills con Kunai a la cabeza.", d: 3},
      {t: "Prohibido usar Suzu para ti misma.", d: 2},
      {t: "Grita «¡KITSUNE!» con cada ulti.", d: 1},
      {t: "Aprovecha la pasiva Médico: cada vez que te cures curando, di «para mí también».", d: 1},
      {t: "Cada vez que hagas Paso veloz hacia un aliado, salúdale con la línea de voz «Hola» al llegar.", d: 1},
      {t: "Gana un 1v1 usando solo Kunai, sin Paso veloz.", d: 2},
      {t: "Toda la partida en posiciones altas a las que llegas trepando.", d: 1},
      {t: "Salva a tres aliados distintos con Suzu en la misma partida.", d: 3},
      {t: "Cada Suzu que no limpie nada: bebe agua.", d: 1}
    ] },
    { id: "lifeweaver", name: "Lifeweaver", role: "support", subrole: "Médico", retos: [
      {t: "Salva a un aliado de una muerte segura con Agarre vital (Life Grip).", d: 2},
      {t: "Salva a dos aliados distintos con Agarre vital en la misma pelea.", d: 3},
      {t: "Tu Plataforma de pétalos tiene que subir a un aliado a una posición alta.", d: 1},
      {t: "Árbol de la vida tiene que salvar al menos a 2 aliados de morir.", d: 3},
      {t: "Prohibido usar Agarre vital con un aliado a vida completa: cada tirón tiene que salvar a alguien herido.", d: 2},
      {t: "Grita «¡PLANTA!» con cada Árbol de la vida.", d: 1},
      {t: "Mata a alguien con las Espinas.", d: 2},
      {t: "Pon la Plataforma de pétalos debajo de tu tanque al empezar cada pelea para darle altura. Avisa por el micro.", d: 2},
      {t: "Toda la partida hablando como influencer de mindfulness.", d: 1},
      {t: "Saca con Agarre vital a un aliado atrapado en un ulti enemigo (Seísmo, Bomba de gravitones, Flujo gravitatorio…).", d: 3},
      {t: "Cada aliado que salves con Agarre vital recibe una flor: haz un spray a sus pies y dile algo bonito.", d: 1},
      {t: "Cada vez que tu Agarre vital mate a un aliado sin querer, 10 sentadillas.", d: 1}
    ] },
    { id: "lucio", name: "Lúcio", role: "support", subrole: "Estratega", retos: [
      {t: "Toda la partida sin tocar el suelo más de 3 segundos seguidos.", d: 3},
      {t: "Barrera sonora tiene que salvar a tu equipo de morir en una pelea.", d: 2},
      {t: "Empuja a un enemigo con Onda de sonido fuera del objetivo en el último segundo.", d: 3},
      {t: "Prohibido cambiar de canción: solo velocidad toda la partida.", d: 1},
      {t: "Grita «¡DROP THE BEAT!» con cada Barrera sonora.", d: 1},
      {t: "Consigue una baja disparando mientras surfeas una pared.", d: 2},
      {t: "Surfea las paredes del mapa entero de una punta a otra sin tocar el suelo.", d: 2},
      {t: "Barrera sonora cayendo desde lo alto (salto desde pared) al menos dos veces en la partida.", d: 2},
      {t: "Toda la partida cantando cada vez que activas Amplificador.", d: 1},
      {t: "Consigue 3 boops que saquen a enemigos del objetivo.", d: 3},
      {t: "Cambia de canción cada vez que el chat escriba «DROP». Si tardas más de 2 segundos, una flexión.", d: 2},
      {t: "Aprovecha la pasiva Estratega: guarda carga extra y usa Barrera sonora dos veces en la misma pelea.", d: 3},
      {t: "Al respawnear, haz el emote de baile de Lúcio en el spawn antes de salir. DJ no se salta el calentamiento.", d: 1}
    ] },
    { id: "mercy", name: "Mercy", role: "support", subrole: "Médico", retos: [
      {t: "Resurrección: resucita a alguien en medio del objetivo y sobrevivid ambos.", d: 3},
      {t: "Mata a alguien con la pistola Blaster Caduceo. Battle Mercy aparece.", d: 2},
      {t: "Usa Flash Heal (Curación rápida) para salvar a un aliado a punto de morir.", d: 2},
      {t: "Toda la partida potenciando: prohibido curar salvo con Flash Heal.", d: 2},
      {t: "Grita «¡HEROES NEVER DIE!» en cada Resurrección.", d: 1},
      {t: "En cada pelea, salta de aliado en aliado con Ángel guardián: si tocas el suelo más de 3 segundos seguidos, una flexión.", d: 2},
      {t: "Potencia a un aliado durante su ulti y que consiga un multi-kill.", d: 2},
      {t: "Cada vez que resucites a alguien, salúdale con la línea de voz «Hola» y haz un spray donde cayó.", d: 1},
      {t: "Resucita a dos aliados en una misma pelea.", d: 3},
      {t: "Toda la partida hablando como doctora alemana: «¡Ja!» en cada cura.", d: 1},
      {t: "Salva al tanque con Flash Heal justo cuando está a 10% de vida.", d: 2},
      {t: "Prohibido Valkyria: guarda el ulti hasta la última pelea.", d: 1}
    ] },
    { id: "mizuki", name: "Mizuki", role: "support", subrole: "Superviviente", retos: [
      {t: "Healing Kasa tiene que rebotar a 3 aliados y volver a ti.", d: 2},
      {t: "Binding Chain tiene que atar a un enemigo que tu equipo remate antes de que se suelte.", d: 2},
      {t: "Katashiro Return: usa la vuelta al muñeco para esquivar una muerte segura.", d: 2},
      {t: "Kekkai Sanctuary tiene que salvar a 2 aliados de morir.", d: 3},
      {t: "Mata a alguien con el Spirit Glaive rebotando en una pared.", d: 3},
      {t: "Grita «¡HASHIMOTO!» cada vez que actives el ulti.", d: 1},
      {t: "Deja el katashiro en un sitio seguro antes de cada pelea y úsalo para volver al menos una vez por pelea.", d: 2},
      {t: "Prohibido tirar el sombrero al tanque: solo a daños y supports.", d: 2},
      {t: "Aprovecha la pasiva Superviviente: tras cada Katashiro Return, di cuánta vida recuperas.", d: 1},
      {t: "Consigue que el Kekkai Sanctuary gane la pelea.", d: 2},
      {t: "Toda la partida hablando como un ninja en misión secreta.", d: 1},
      {t: "Cada vez que tu Kasa vuelva a tu cabeza, haz una reverencia (agáchate) antes de lanzarla de nuevo.", d: 2}
    ] },
    { id: "moira", name: "Moira", role: "support", subrole: "Médico", retos: [
      {t: "Orbe biótico de daño tiene que matar a alguien.", d: 2},
      {t: "Coalescencia tiene que matar a 2 enemigos y curar a 3 aliados a la vez.", d: 3},
      {t: "Usa Desvanecer para salvarte de una muerte segura y vuelve a la pelea en 3 segundos.", d: 2},
      {t: "Toda la partida sin usar el orbe de curación: solo el de daño.", d: 2},
      {t: "Grita «¡CIENCIA!» con cada Coalescencia.", d: 1},
      {t: "Consigue 3 kills en una misma vida con el agarre biótico.", d: 3},
      {t: "Gana un 1v1 solo con el agarre biótico, sin orbes.", d: 2},
      {t: "Toda la partida hablando como científica loca.", d: 1},
      {t: "Aprovecha la pasiva Médico: cura mucho para curarte a ti mismo en un 1v1 que parecía perdido.", d: 2},
      {t: "Prohibido Desvanecer para escapar: solo para entrar.", d: 2},
      {t: "Tras cada kill, di «experimento completado» y pon un spray sobre la muestra.", d: 1},
      {t: "Orbe biótico de daño rebotando en paredes y matando a 2.", d: 3}
    ] },
    { id: "wuyang", name: "Wuyang", role: "support", subrole: "Superviviente", retos: [
      {t: "Tidal Blast tiene que salvar a tu tanque y tumbar a 3 enemigos.", d: 3},
      {t: "Guardian Wave tiene que sacar a 2 enemigos del objetivo.", d: 3},
      {t: "Toda la partida surfeando con Rushing Torrent: si andas más de 3 segundos, bebe agua.", d: 2},
      {t: "Controla un orbe de agua en el aire para doblar una esquina y matar a alguien.", d: 3},
      {t: "Grita «¡OLA!» (sin h) cada vez que uses Guardian Wave.", d: 1},
      {t: "Toda la partida sin usar Restorative Stream: tendrás que curar con el resto del kit.", d: 2},
      {t: "Gana un 1v1 usando solo orbes de agua, sin Rushing Torrent.", d: 2},
      {t: "Toda la partida hablando del agua, el mar y los peces. El chat decide si cuenta.", d: 1},
      {t: "Salva a un aliado de la muerte con Tidal Blast encerrándolo en agua.", d: 2},
      {t: "Cada vez que surfees hasta un aliado herido, salúdale con la línea de voz «Hola» antes de curarle.", d: 1},
      {t: "Aprovecha la pasiva Superviviente: tras cada Rushing Torrent, recupera vida y dilo.", d: 1},
      {t: "Consigue 3 kills con orbes cargados.", d: 3}
    ] },
    { id: "zenyatta", name: "Zenyatta", role: "support", subrole: "Estratega", retos: [
      {t: "Transcendencia tiene que salvar a tu equipo de morir en una pelea. El chat lo valida.", d: 3},
      {t: "Orbe de discordia siempre al tanque enemigo: prohibido cambiar de objetivo.", d: 1},
      {t: "Gana un 1v1 cuerpo a cuerpo rematando con la patada de Zenyatta.", d: 2},
      {t: "Empuja con la patada a un enemigo fuera del objetivo y remátalo con esferas.", d: 3},
      {t: "Grita «¡EXPERIMENTA LA TRANQUILIDAD!» en cada Transcendencia, a la vez que Zenyatta.", d: 1},
      {t: "Toda la partida hablando como monje zen: todo con paz y calma, aunque perdáis.", d: 1},
      {t: "Consigue 3 kills con esferas cargadas.", d: 3},
      {t: "Cambia el orbe de armonía solo cuando el aliado anterior esté a vida completa. El chat vigila.", d: 2},
      {t: "Antes de cada pelea, medita: haz el emote de meditar 3 segundos en el spawn o tras una esquina.", d: 1},
      {t: "Consigue una baja con una esfera cargada a más de 30 metros.", d: 3},
      {t: "Cada vez que mueras, di «la iluminación está cerca».", d: 1},
      {t: "Usa el orbe de armonía solo en el tanque durante la primera ronda.", d: 2}
    ] }
  ],
  generales: [
    {t: "Toda la partida narrando tus jugadas en tercera persona, como un comentarista de fútbol.", d: 1, cat: "comunicacion"},
    {t: "Solo puedes comunicarte con el equipo usando las líneas de voz y el sistema de avisos (ping). Nada de micro con tu equipo.", d: 2, cat: "comunicacion"},
    {t: "Antes de cada pelea, predice en voz alta quién va a morir primero. Si aciertas 3, el chat te debe un aplauso.", d: 1, cat: "comunicacion"},
    {t: "Cada vez que pidas algo al equipo, tiene que ser rimando. Sin rima, no hay petición.", d: 2, cat: "comunicacion"},
    {t: "Habla todo el rato con acento andaluz exagerado. Si se te escapa el normal, bebe agua.", d: 1, cat: "comunicacion"},
    {t: "Tienes que usar el botón de «Elogiar» a cada compañero antes de que termine la partida.", d: 1, cat: "comunicacion"},
    {t: "Prohibido decir «tío», «bro» o «en plan» durante toda la partida. Cada vez que se escape, una sentadilla.", d: 2, cat: "comunicacion"},
    {t: "Cada vez que un enemigo te mate, léele su nombre al chat con voz de presentador de boxeo mientras ves la killcam.", d: 1, cat: "comunicacion"},
    {t: "Haz de shotcaller: antes de cada pelea tienes que decir el plan en voz alta en una sola frase.", d: 2, cat: "comunicacion"},
    {t: "Prohibido andar hacia atrás: solo puedes moverte hacia delante y de lado.", d: 3, cat: "movimiento"},
    {t: "Tienes que saltar cada vez que recargues. Recargar en el suelo: una flexión.", d: 1, cat: "movimiento"},
    {t: "Toda la partida agachado cuando no estés en combate: te mueves como un ninja entre peleas.", d: 1, cat: "movimiento"},
    {t: "Tienes que ir al pack de vida grande más cercano después de cada respawn antes de ir a la pelea.", d: 1, cat: "movimiento"},
    {t: "Prohibido usar el mismo camino dos veces desde el spawn: cada respawn, una ruta nueva.", d: 2, cat: "movimiento"},
    {t: "Tras cada kill, tienes que cambiar de posición al menos 10 metros antes de volver a disparar.", d: 2, cat: "movimiento"},
    {t: "Toda la partida en la posición más alta posible del mapa para tu héroe.", d: 2, cat: "movimiento"},
    {t: "Prohibido saltar en toda la partida.", d: 3, cat: "movimiento"},
    {t: "Solo puedes girar la cámara hacia la derecha. Para mirar a la izquierda, da la vuelta completa.", d: 3, cat: "movimiento"},
    {t: "Sensibilidad al doble durante toda la partida.", d: 2, cat: "controles"},
    {t: "Sensibilidad a la mitad durante toda la partida.", d: 2, cat: "controles"},
    {t: "Invierte el eje Y del ratón o del mando toda la partida.", d: 3, cat: "controles"},
    {t: "Juega con el FOV al mínimo toda la partida.", d: 2, cat: "controles"},
    {t: "Juega con la calidad gráfica al mínimo y la escala de renderizado al 50 % toda la partida.", d: 2, cat: "controles"},
    {t: "Juega sin mira (crosshair) toda la partida: ponla invisible en ajustes.", d: 3, cat: "controles"},
    {t: "Mira de color rosa chicle gigante toda la partida. El chat elige el tamaño.", d: 1, cat: "controles"},
    {t: "Intercambia las teclas de habilidad 1 y 2 durante toda la partida.", d: 2, cat: "controles"},
    {t: "Durante la primera ronda, muévete con las flechas del teclado en lugar de WASD.", d: 3, cat: "controles"},
    {t: "Mueve el ratón con la mano que no usas nunca durante la primera ronda.", d: 3, cat: "controles"},
    {t: "Cada vez que un compañero muera, tienes que ir a su sitio de muerte y hacer un spray en su honor.", d: 1, cat: "equipo"},
    {t: "Al empezar cada ronda, elige un compañero «protegido»: si muere antes que tú, 5 flexiones.", d: 2, cat: "equipo"},
    {t: "Pide a tu equipo que elija tu próximo héroe si pierdes la primera ronda. Y respétalo.", d: 2, cat: "equipo"},
    {t: "Tienes que seguir siempre al tanque de tu equipo: nunca más de 15 metros de él.", d: 2, cat: "equipo"},
    {t: "Elige a un compañero al empezar y anímalo con un mensaje positivo cada vez que muera.", d: 1, cat: "equipo"},
    {t: "Elige a un compañero de daño al empezar: todas tus kills tienen que ser sobre el enemigo al que él esté disparando.", d: 2, cat: "equipo"},
    {t: "Pide a tu equipo que hagáis un emote juntos al empezar la partida. Si lo consigues, el chat te regala inmunidad a un castigo.", d: 1, cat: "equipo"},
    {t: "Cada vez que un compañero pida curación con el aviso del juego, tienes que responder «¡YA VA!» por el micro y curarle en 3 segundos.", d: 1, cat: "equipo", roles: ["support"]},
    {t: "Tienes que curar a todos los compañeros al menos una vez cada pelea. El chat vigila la barra.", d: 2, cat: "equipo", roles: ["support"]},
    {t: "Sé el primero en pisar el objetivo en cada pelea.", d: 2, cat: "equipo", roles: ["tank"]},
    {t: "Protege a tu support más débil: cada vez que muera, bebe agua.", d: 2, cat: "equipo", roles: ["tank","damage"]},
    {t: "Cada muerte: una flexión. Si mueres más de 8 veces, sentadillas en vez de flexiones.", d: 1, cat: "castigo"},
    {t: "Cada muerte: un trago de agua. Hidratación obligatoria.", d: 1, cat: "castigo"},
    {t: "Cada vez que te maten por la espalda, tienes que hablar con voz de pito durante 1 minuto.", d: 1, cat: "castigo"},
    {t: "Si pierdes la primera ronda, la segunda la juegas de pie.", d: 2, cat: "castigo"},
    {t: "Cada vez que mueras, el chat elige una palabra prohibida hasta el final de la partida.", d: 2, cat: "castigo"},
    {t: "Cada ulti desperdiciado (sin kill ni efecto): 10 sentadillas al acabar.", d: 2, cat: "castigo"},
    {t: "Cada vez que caigas al vacío, tienes que cantar el estribillo de una canción elegida por el chat.", d: 1, cat: "castigo"},
    {t: "Si acabas con más muertes que kills, mañana abres el stream con una canción de karaoke.", d: 3, cat: "castigo"},
    {t: "El chat elige tu héroe cada vez que mueras. Si cambias sin orden, 5 flexiones.", d: 3, cat: "caos"},
    {t: "Tienes que usar el ulti en cuanto lo tengas, sin esperar. Da igual la situación.", d: 2, cat: "caos"},
    {t: "Toda la partida usando la skin más fea que tengas del héroe que juegues. El chat decide cuál es la más fea.", d: 1, cat: "caos"},
    {t: "Cambia de héroe cada vez que consigas una kill.", d: 3, cat: "caos"},
    {t: "Tienes que hacer un emote en mitad de cada pelea. Aunque te maten.", d: 2, cat: "caos"},
    {t: "Spray obligatorio en cada esquina que pases antes de entrar a pelear.", d: 1, cat: "caos"},
    {t: "Juega con música a todo volumen y sin sonido del juego durante la primera ronda.", d: 3, cat: "caos"},
    {t: "Cada vez que el chat escriba «CAMBIO», tienes que cambiar de héroe en el siguiente respawn.", d: 2, cat: "caos"},
    {t: "Tienes que pisar el objetivo o la carga en cada pelea, aunque sea solo un segundo.", d: 1, cat: "objetivo"},
    {t: "Juega la partida entera sin salir del área del objetivo, salvo al respawnear.", d: 2, cat: "objetivo"},
    {t: "Pisa el objetivo el primero de tu equipo al empezar cada ronda. Si alguien llega antes, una flexión.", d: 2, cat: "objetivo"},
    {t: "Cada vez que el objetivo quede sin nadie de tu equipo encima más de 5 segundos, bebe agua. Tú eres el guardián.", d: 2, cat: "objetivo"},
    {t: "Cada vez que tu equipo gane una pelea, pon un spray en el objetivo antes de que empiece la siguiente.", d: 1, cat: "objetivo"},
    {t: "Haz un emote encima del objetivo al menos una vez por ronda, en mitad de la partida. Si te matan haciéndolo, cuenta igual.", d: 1, cat: "objetivo"},
    {t: "Quédate en el objetivo 10 segundos seguidos sin salir durante una pelea, pase lo que pase.", d: 3, cat: "objetivo"}
  ]
};
